[phases.setup]
nixPkgs = ["maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/stock-prediction-system-1.0.0.jar"
