[phases.setup]
nixPkgs = ["maven", "openjdk11"]

[phases.install]
cmds = ["mvn dependency:resolve"]

[phases.build]
cmds = ["mvn clean package -DskipTests -Dmaven.test.skip=true"]

[start]
cmd = "java -jar target/stock-prediction-system-1.0.0.jar"
