[phases.setup]
nixPkgs = ["maven", "openjdk11"]

[phases.install]
cmds = ["mvn dependency:resolve -DskipTests"]

[phases.build]
cmds = ["mvn clean package -DskipTests -Dmaven.test.skip=true -Dmaven.compiler.source=11 -Dmaven.compiler.target=11"]

[start]
cmd = "java -Dspring.profiles.active=railway -Xmx512m -Xms256m -jar target/stock-prediction-system-1.0.0.jar"
