spring:
  application:
    name: stock-prediction-system
  
  # Database Configuration (H2 in-memory)
  datasource:
    url: jdbc:h2:file:${user.home}/ckps/stockdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # H2 Console disabled
  h2:
    console:
      enabled: false

# Server Configuration
server:
  port: ${PORT:8080}

# Logging
logging:
  level:
    root: WARN
    com.stockprediction: INFO
