spring:
  application:
    name: stock-prediction-system
  
  # Database Configuration for Production (using H2 for simplicity)
  datasource:
    url: jdbc:h2:file:./data/stockdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # Disable H2 Console in production
  h2:
    console:
      enabled: false

# Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# Logging
logging:
  level:
    com.stockprediction: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

# CORS Configuration for Production
cors:
  allowed-origins: ${FRONTEND_URL:https://your-frontend-domain.vercel.app}
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
